spring.application.name=quanlybenhvien

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/quanlybenhvien?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=duy31082006

spring.thymeleaf.cache=false
