spring.application.name=quanlybenhvien

# Cổng chạy ứng dụng
server.port=8080

# Kết nối MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/quanlybenhvien?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=duy31082006

# Thymeleaf không cache (để sửa HTML thấy ngay)
spring.thymeleaf.cache=false